# @package pi

_target_: policy_learner.EasyBCQLearner
name: pi_easy_bcq

load_path: null
model_save_path: ${path}/models/${name}_${pi.name}_${env.domain}.pt

device: ${device}
discount: ${discount}

# alg specific parameters
n_samples: 10

# logging 
format_str: "Pi Train: Step {values[step]:8.0f}, Eval Return {values[return]:4.4f}"



# for compatibility
# batch_size: 512
# lr: 1e-4
# state_dim: ${state_dim}
# action_dim: ${action_dim}
# dist_type: trunc