# @package _global_
name: train_${env.name}_${seed}

path: /Users/davidbrandfonbrener/code/onestep-rl #???

defaults:
  - beta: bc
  - q: sarsa
  - pi: reverse_kl
  - baseline: td #value_sample

# which learners to train
train_beta: true
train_q: true
train_pi: true
train_baseline: true

# model params
beta:
  load_path: null
q:
  load_path: null
  model_save_path: ${path}/models/${name}_q
pi:
  load_path: null
  model_save_path: ${path}/models/${name}_pi
baseline:
  load_path: null
  model_save_path: ${path}/models/${name}_baseline

# train loop hyperparameters
beta_steps: 10 #5e5
baseline_steps: 1e5 #0
steps: 1
q_steps: 10 #2e6
pi_steps: 10 #1e5

beta_save_freq: 1e5
pi_save_freq: 1e6
q_save_freq: 1e6
log_freq: 2e3

eval_samples: 1000
eval_episodes: 1
log_dir: ${path}/logs/${name}

seed: 0
device: cpu

# data parameters
data_path: ${path}/data/${env.name}.pt
env_type: d4rl
env:
  name: halfcheetah-medium-v2
discount: 0.99
state_dim: ???
action_dim: ???

# hydra parameters
hydra/hydra_logging: none
hydra/job_logging: none
hydra:
  output_subdir: null
  run:
    dir: .
  job:
    config:
      override_dirname:
        exclude_keys:
          - name